### ISSUE TITLE
Repeated prompt

### ISSUE THREAD

**Issue by grant** [derhuerst/select-prompt#1]
The prompt repeats (using arrow keys to change underline).
```
node select.js
? What is your favorite color? ›
? What is your favorite color? ›
? What is your favorite color? ›
? What is your favorite color? ›
? What is your favorite color? ›
- red
- yellow
- green
- blue
- black
- white
✔ What is your favorite color? › blue
Submitted with #00f
```

Are there special terminal settings that we need to set to delete previous lines and stop this behavior?

**Comment by derhuerst** [comment]
`select-prompt` sends special characters to the terminal that clear the line or move the cursor. I assume that [the computation of these in `select-prompt`](https://github.com/derhuerst/select-prompt/blob/30eb4298659aecf803f3e275077d5951468054f0/index.js#L76) has a bug. It might be smarter to upgrade to `promp-skeleton@1`, which uses [`ansi-diff-stream`](https://www.npmjs.com/package/ansi-diff-stream) to compute the special characters.

**Comment by derhuerst** [comment]
Sometimes this behaviour is also a result of buggy terminal emulators though.

**Comment by derhuerst** [comment]
I'm deprecating this prompt in favour of the [select prompt of `enquirer`](https://github.com/enquirer/enquirer#select-prompt). Please try your luck there.
